const PAYSTACK_API_URL = 'https://api.paystack.co';

const getSecretKey = () => {
  if (!process.env.PAYSTACK_SECRET_KEY) {
    throw {
      statusCode: 500,
      message: 'Paystack is not configured. Set PAYSTACK_SECRET_KEY.'
    };
  }

  return process.env.PAYSTACK_SECRET_KEY;
};

const requestPaystack = async (path, options = {}) => {
  console.log(`[Paystack] ${options.method || 'GET'} ${path}`);

  const response = await fetch(`${PAYSTACK_API_URL}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${getSecretKey()}`,
      'Content-Type': 'application/json',
      ...(options.headers || {})
    }
  });

  const result = await response.json();

  console.log(`[Paystack] Response ${response.status}: ${JSON.stringify({
    status: result.status,
    message: result.message,
    data: result.data
      ? {
          reference: result.data.reference,
          status: result.data.status,
          amount: result.data.amount,
          gateway_response: result.data.gateway_response
        }
      : undefined
  })}`);

  if (!response.ok || !result.status) {
    throw {
      statusCode: 502,
      message: result.message || 'Paystack request failed'
    };
  }

  return result.data;
};

const initializeTransaction = ({
  email,
  amount,
  reference,
  callbackUrl,
  metadata
}) => {
  console.log(`[Paystack] Initialize reference: ${reference || '[generated by Paystack]'}`);
  console.log(`[Paystack] Initialize callback_url: ${callbackUrl}`);

  return requestPaystack('/transaction/initialize', {
    method: 'POST',
    body: JSON.stringify({
      email,
      amount: Math.round(amount * 100),
      currency: 'NGN',
      reference,
      callback_url: callbackUrl,
      metadata
    })
  });
};

const verifyTransaction = (reference) => {
  console.log(`[Paystack] Verifying transaction: ${reference}`);
  return requestPaystack(`/transaction/verify/${encodeURIComponent(reference)}`);
};

module.exports = {
  initializeTransaction,
  verifyTransaction
};